apiVersion: v1
kind: Service
metadata:
  name: batch-visualizer-frontend-app-service
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 80
  selector:
    app: batch-visualizer-frontend-app
  type: NodePort