apiVersion: v1
kind: Service
metadata:
  name: batch-visualizer-backend-migrator-service
spec:
  ports:
    - name: "8080"
      port: 8081
      targetPort: 8080
  selector:
    app: batch-visualizer-backend-migrator
  type: NodePort