apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-visualizer-backend-migrator-cronjob
spec:
  schedule: '0 * * * *'
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch-visualizer-backend-migrator
              image: twofootdog/project-repo:batch-visualizer-backend-migrator
              command: ["bin/sh", "-c"]
              args: ["requestDate=$(date '+%Y%m%d%H%M%S'); java -jar -Dspring.profiles.active=dev -Duser.timezone=KST /app.jar --job.name=BatchVisualizerJob version=VERSION_STRING requestDate=$requestDate"]
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
              env:
                - name: VERSION
                  value: 'VERSION_STRING'
                - name: DATE
                  value: 'DATE_STRING'
              volumeMounts:
                - mountPath: /etc/localtime
                  name: timezone-config
          volumes:
            - hostPath:
                path: /usr/share/zoneinfo/Asia/Seoul
              name: timezone-config
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: my-secret