#apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: batch-visualizer-backend-provider-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-visualizer-backend-provider
  template:
    metadata:
      labels:
        app: batch-visualizer-backend-provider
    spec:
      containers:
        - name: batch-visualizer-backend-provider
          image: twofootdog/project-repo:batch-visualizer-backend-provider
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: VERSION
              value: 'VERSION_STRING'
            - name: DATE
              value: 'DATE_STRING'
          volumeMounts:
            - mountPath: /etc/localtime # pod 내 시간 변경을 위함(UTC->KST)
              name: timezone-config
      volumes:
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
          name: timezone-config
      imagePullSecrets:
        - name: my-secret