apiVersion: v1
kind: Service
metadata:
  name: batch-visualizer-backend-provider-service
spec:
  ports:
    - name: "8080"
      port: 8084
      targetPort: 8080
  selector:
    app: batch-visualizer-backend-provider
  type: NodePort 